controllers:
    resource: ../../src/Controller/api/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation

api_login_check:
    path: /api/login_check

api_login:
    path: /login
